### ISSUE TITLE
Add openinfra day conference contribution entry from A.Diab to website 

### ISSUE THREAD

**Issue by alexander-diab** [SovereignCloudStack/website#1028]
Add on scs website 

https://scs.community/conferences/
in section
Conference Contributions (English)

Event title: Openinfra Day Hungary
Event Date: June 3, 2024

Talk Title: sovereign cloud stack and open services cloud - a powerful couple

Speakers: Alexander Diab, Swaroop Raghupathy

Video Link: https://www.youtube.com/watch?v=2pNo8F3AMrw

Slides are attached to this issue
[scs-osc-alex-oif-20240603.pdf](https://github.com/user-attachments/files/17209632/scs-osc-alex-oif-20240603.pdf)

**Comment by scoopex** [comment]
See https://github.com/SovereignCloudStack/website/pull/1053
