### ISSUE TITLE
Menu button on mobile devices

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/website#103]
The navigation menu should collapse to a menu button on mobile devices for a cleaner look of the website.

![2021-07-15 09_42_21-Window](https://user-images.githubusercontent.com/29982899/125749336-50d324ca-efb8-4ad1-9db3-a596015660ba.png)

I recommend to keep the most important social icons within the navigation menu, e.g. something like this:

![2021-07-15 09_42_21-Window](https://user-images.githubusercontent.com/29982899/125750205-5f5b76fd-c04c-437c-b2e4-953ce0b696f7.png)

**Comment by garloff** [comment]
Agree.
Pull Request very welcome.
(I will invest some more time on our page generation automation probably to remove more duplication -- but I'm in generally not so skilled in CSS/HTML. So I will not be able to invest time into investigating how to implement your proposal myself anytime soon ...)
Note: We can also pull things into the staging branch now and access via https://staging.scs.community/ if a local build is not good enough for testing.
