### ISSUE TITLE
Add form to subscribe to Mailman3 announce mailing list

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/website#201]
We want to lead as many users as possible to subscribe to our [announce](https://scs.sovereignit.de/mailman3/postorius/lists/announce.lists.scs.community/) mailing list. We thus should have a form or highlighted button on the landing page redirecting users to the subscription page of this mailing list.

I already tried to implement a simple form in the footer but struggled with the CSRF-Token check implemented by Django, see https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/KAPI35V45PJQ7ORS6HJQVS3VTP4ZI5RE/

**Comment by fkr** [comment]
Imho I would just make sure the mailman form is easily found and spend a whole lot of time on this.
