### ISSUE TITLE
Add pagination to news page

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/website#202]
As the number of posts rises, we will certainly need [Pagination](https://getbootstrap.com/docs/5.0/components/pagination/) for the news site.

General question: Would you prefer one pagination per section (announcements, blog posts, media coverage, etc.) or single pagination for the whole news page?

**Comment by itrich** [comment]
I'm thinking of a paginated list with multiple javascript-enabled filters/categories in the head line. What do you think?

**Comment by itrich** [comment]
Do we need this? What do you think about scrolling a long page vs. pagination on the news section? @fkr @garloff ?

**Comment by garloff** [comment]
As we keep latest things on top, pagination is less critical in my opinion. Except that we have multiple sections and thus the secondary sections will be hidden by the first section getting too long...
This would suggest pagination per section.

**Comment by fkr** [comment]
Am with @garloff, pagination per section.
