### ISSUE TITLE
Add security.txt to web site

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/website#211]
Our [security advisory for log4j](https://scs.community/2021/12/13/advisory-log4j/) says
"Please contact the SCS project management team at project at scs dot sovereignit dot de to ask security questions or report security issues."
which is good, as we at least clearly communicate the communication channels.

Better would be to have a security-specific address (alias) that also offers encrypted contact options (PGP and maybe additional options). And to use a standardized way to advertize this using the security.txt standard.
See https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12 and https://securitytxt.org/ .

**Comment by itrich** [comment]
Good point! We should also add this information as `SECURITY.MD` to at least the most frequently used repositories in the SovereignCloudStack namespace. 

Should we offer a public PGP key on our website? Who is going to hold the key?

**Comment by fkr** [comment]
👍 on the SECURITY.MD (Docs/ at least, some other repos are going to be merged and archived anyways).
For the GPG key, I'd say the Product Board can appoint those people?

**Comment by itrich** [comment]
The PR #212 adds a security-related RSS feed to which one may subscribe if needed.

**Comment by itrich** [comment]
We should also hint these information here: https://github.com/SovereignCloudStack in the repository: `SovereignCloudStack/.github`

**Comment by itrich** [comment]
See: https://scs.community/feed/security.xml
