### ISSUE TITLE
Replace BMWi with BMWK

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/website#220]
We should replace all occurrences of BMWi with BMWK. Moreover, the _"funded by the BMWi"_-Logo needs to be replaced by a newer version as soon as it gets released.

**Comment by berendt** [comment]
Is BMWK the official short form? On Wikipedia it is still BMWi. Press releases after the renaming continue to refer to the BMWi.

**Comment by berendt** [comment]
According to https://www.protokoll-inland.de/Webs/PI/DE/rang-titulierung/amtliche-reihenfolgen/bundesministerien/liste-der-bundesministerien-node.html BMWK is the correct new short form.

**Comment by itrich** [comment]
Note to myself: Download the "Logo with Förderzusatz" here: https://styleguide.bundesregierung.de/sg-de/suche/bildwortmarken-von-bundesregierung-und-behoerden-mit-foerderzusatz-fz--317634

**Comment by itrich** [comment]
> Note to myself: Download the "Logo with Förderzusatz" here: https://styleguide.bundesregierung.de/sg-de/suche/bildwortmarken-von-bundesregierung-und-behoerden-mit-foerderzusatz-fz--317634

The download link is private. We should get the package from VDI.
