### ISSUE TITLE
use a static generator for the website

### ISSUE THREAD

**Issue by curx** [SovereignCloudStack/website#29]
Maybe it is useful to have a static website build and pipeline for the website, e.g https://gohugo.io ?

/cc: @garloff

**Comment by berendt** [comment]
Yes. But is not a priority. For the moment it works. I think later on we will rather switch to something more dynamic.

**Comment by berendt** [comment]
I have ported the website for 23T to Hugo. The theme is under https://github.com/23technologies/hugo-theme-23technologies, the website under https://github.com/23technologies/website. This can be adapted accordingly here.

**Comment by itrich** [comment]
While I've only worked with Jenkins so far, I'll soon be joining the SCS team and start with adopting @berendt's Hugo theme to the SCS layout. In addition, I'll build up various Github Action pipelines for easier testing and deployment of the genereated site. I'll reach out again very soon! 👋

**Comment by berendt** [comment]
@itrich Let's first discuss whether the Hugo makes sense and will be sufficient in the future. We now use Grav CMS (https://getgrav.org) for our pages. This is also static and can be managed via Git. But it brings a lot more comfort and functions with it.
