### ISSUE TITLE
Providing the OIF Summit slides on our blog post

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/website#325]
We have collected the various talks our community is giving at the OpenInfra Summit 2022 on our blog: <https://scs.community/2022/06/02/scs-at-oifsummit2022>.

Please upload - if you like - your slides until Monday evening to our website repository and I will link them to the corresponding schedule item in our blog post. This will boost the traffic on our website and hopefully on our social media accounts. 

It would be great if you create a huge QR code at the end of your presentation so that visitors can directly receive the shown slides deck. The deep links are already available.

Thank you for contributing to OIF Summit and being part of our joint actions at this exciting event. Looking forward to seeing you next week!

@fkr @berendt @horazont @garloff @matfechner

**Comment by horazont** [comment]
"oops". :-).

I'll ask Felix if he can provide the slides now at least.

**Comment by berendt** [comment]
Add our slides as well.
