### ISSUE TITLE
add the social media image to the general blog post template

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/website#344]
When we add a social media image in the blog post this should be displayed in the post itself as well.
Discussed with @itrich in #343

**Comment by itrich** [comment]
Some thoughts:
- We should make this optional. Some postings (e.g. https://scs.community/2022/06/27/parldigi/) would then consist of more graphics than text.
- How to deal with old postings that already have an image included (manually?)
- I'm thinking of adding the image as background for the head area, something comparable to the carousel: blurry image with title and author & timestamp as overlay.

**Comment by itrich** [comment]
> Member

The more I think about this issue, the more I tend to close this issue as *Won't do*. I found no reasonable way how to deal with all three items above and not adding further frontmatter options at the same time. Any opinions?
