### ISSUE TITLE
Website is not updated even though build and deploy actions run through

### ISSUE THREAD

**Issue by maxwolfs** [SovereignCloudStack/website#697]
All recent merged Pull Requests on `main` triggered the [Build Production website](https://github.com/SovereignCloudStack/website/actions/workflows/build-production.yml) action. All jobs are completed and the final html build files are pushed to the [gh-pages branch](https://github.com/SovereignCloudStack/website/tree/gh-pages), but the website on https://scs.comunity is not updated.

This is probably related to the machine serving the webpage.

**Comment by scoopex** [comment]
@maxwolfs is that still relevant? I never experienced that. Please reopen if necessary.
