### ISSUE TITLE
Blog post on hashicorp's BSL changes

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/website#725]
Refer to the facts and to what others have written, in particular https://blog.gruntwork.io/the-future-of-terraform-must-be-open-ab0b9ba65bca.
Just explain that this was not a surprise to us, as we've seen the risk (applying our [OSS-Health-Check](https://github.com/SovereignCloudStack/standards/blob/main/Drafts/OSS-Health.md)).
And list where we are using terraform and vault (but not nomad, vagrant, consul, ...)
https://github.com/SovereignCloudStack/minutes/blob/main/product-board/20230814.md#hashicorps-sblsbul
And tell what we will do:
* Short term: ensure that we keep using the free versions and advise our customers to do so
  - Have e.g. added a terraform version requirement < 1.6 into k8s cluster mgmt server creation logic (which uses tf)
* Medium term: see that we can support and use forks that remain free
  - Failing that we would need to replace the functionality by using other tools

**Comment by berendt** [comment]
Please also mention the Terraform Registry TOS change: https://github.com/opentffoundation/roadmap/issues/24#issuecomment-1699535216

**Comment by garloff** [comment]
This is old news now and won't happen unless we have a specific reasson to revisit this.
