### ISSUE TITLE
CiaB as edge appliance

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/website#729]

**Comment by rholling** [comment]
Maybe we have a use case for this idea that we could illustrate well.
We designed and built a prototype for our lab intended for automation in discrete manufacturing (less important now). But: the software that records the process and system data is currently running on a local workstation. We would like to virtualize this computer and run it as an edge solution (VM). The SW part in the VM in the edge device communicates than with the software in our private cloud (still pure OpenStack).
Maybe that's a possibility? Above all, this is a possibility that we could realize in the short term - alongside all other activities...
Feedback welcome.

**Comment by fkr** [comment]
Indeed, thanks @rholling - imho there are several good use-cases for CiaB as an edge appliance.
I'd actually like to also look into being able to orchestrate a set of CiaBs (moving this closer towards being actually an edge solution). Other setups could benefit from this as well, since one CiaBs is basically like one single scs deployment being able to orchestrate multiple of them (and having things like observability across all of them, ...) would be really nice.
