### ISSUE TITLE
Marc and several supporting companies are missing from the map on the SCS website

### ISSUE THREAD

**Issue by manuela-urban** [SovereignCloudStack/website#756]
The following companies are missing on the map: AOV IT.services, arctodix, Daiteap, JH-Computers, Proventa, ScaleUp Technologies, StackXperts

**Comment by frosty-geek** [comment]
ref #751

**Comment by maxwolfs** [comment]
Place for adding further employees: https://github.com/SovereignCloudStack/website/tree/main/_employees
Place for adding further community profiles: https://github.com/SovereignCloudStack/website/tree/main/_members
Place for adding further partners: https://github.com/SovereignCloudStack/website/tree/main/_partners
Place for adding further supporting partners: https://github.com/SovereignCloudStack/website/blob/main/_data/supporter.yml
Place for adding further providers: https://github.com/SovereignCloudStack/website/blob/main/_data/provider.yml

**Comment by scoopex** [comment]
- added Marc
- created a follow-up task #769
