### ISSUE TITLE
Add MB Foss Conference Talk to the homepage

### ISSUE THREAD

**Issue by alexander-diab** [SovereignCloudStack/website#842]
Please add an an entry in the section "Konferenzbeiträge (Englisch)" with the following details: 

Conference Title: Mercedes-Benz FOSS Con 2023 
Date: 7.Oktober 2023
Talk Title: Standardizing an open source cloud computing stack – benefits and drawbacks

Slides can be found here : https://ms.scs.sovereignit.de/nextcloud/f/332410

The entry may refer to this page: https://opensource.mercedes-benz.com/convention/

**Comment by scoopex** [comment]
https://github.com/SovereignCloudStack/website/pull/845
