### ISSUE TITLE
events page updaten

### ISSUE THREAD

**Issue by alexander-diab** [SovereignCloudStack/website#875]
Bitte den Paragraphen SCS Summits auf der Seite 
https://scs.community/de/events/
mit folgendem Text ersetzen:
"
SCS Summits
Nach dem großen Erfolg (https://scs.community/summit2023/)   vom letzten Jahr findet das nächste  [SCS Summit 2024](https://scs.community/summit2024) am 14.5.2024 wieder in Berlin statt. In Kürze werden wir auf der Veranstaltungsseite weitere Informationen zum Programm und dem Veranstaltungsort veröffentlichen. Das Summit wird - wie auch letztes Jahr wieder größtenteils  deutschsprachig sein mit Entscheidungsträgern aus Politik und Wirtschaft als primärer Zielgruppe. Am Folgetag findet am selben Ort der [Open Infra Day](https://openstack.org/events/openstackdays#tab=events_tab) Germany statt, mit weitestgehend englischsprachigen Inhalten und einer eher technischen Ausrichtung.
"
... und auf https://scs.community/events/
folgendes: 
"
After last year's great success (https://scs.community/summit2023/), the next SCS Summit 2024 (https://scs.community/summit2024) will take place again in Berlin on May 14, 2024. We will publish further information about the program and the venue on the event page shortly. As last year, the summit will again be largely in German focussing decision makers from politics and business. On the following day, the Open Infra Day Germany (https://openinfra.dev/days#tab=events_tab) will take place at the same venue, with primarily in English and a more technical focus.
"
(FZ bitte hier den Absatz "Hackathons" updaten und dann an Max oder Marc oder wen auch immer assignen)

**Comment by FriederikeZelke** [comment]
"Hackathons" are already done, Kurt changed the text directly.

**Comment by garloff** [comment]
English language requests are preferred.
Thanks for the text input, I used it for #886.
