### ISSUE TITLE
Write blogpost on costs of making a cluster SCS-compliant 

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/website#900]
See [Adaption Cost](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md)

**Comment by cah-hbaum** [comment]
The blogpost is underway now, @martinmo and me already wrote most of it.
We set the date for this to the 13-05-2024, hopefully we can get an approval for the post by this time.
