### ISSUE TITLE
summit program 2024 publishing

### ISSUE THREAD

**Issue by alexander-diab** [SovereignCloudStack/website#913]
Hi Folks,
I have found the following files in the website repo, of which the framework retrieves information for the program 2023.

https://github.com/SovereignCloudStack/website/blob/main/_data/summit2023-talks.yml

the attribute
- day
is not required in 2024
the attribute
- speaker
is empty. Instead "description" is used for the name of the speaker. Perhaps because of the possibility to have two lines, one for "de" and "en".
the attribute
- location
I do not remember anymore why we had it and how this displayed. We need to check this.
the attribute
- avatar
should be possible activate by placing a folder in the assets/images folder like
summit2024/speaker/
and to point at an image like
summit2023/speaker/rafael-laguna.jpg
once we have checked, how the attributes are displayed when compiled, I can fill up the file with data.
The attributes
- slides
- video
we only need after the summit

Additionally there is a page, where all speakers are displayed

https://github.com/SovereignCloudStack/website/blob/main/_data/summit2023.yml

This should be pretty straight forward.

**Comment by scoopex** [comment]
I have created a draft-branch and a pull request fro that:
https://github.com/SovereignCloudStack/website/pull/914

@alexander-diab and @reginametz , please add the scheduled talks here: https://github.com/SovereignCloudStack/website/blob/summit2024_schedule/_data/summit2024.yml
